version: '2'
services:
  my-webapp:
    build: my-webapp/.
    links:
    - mysql-server
    ports:
    - "80:8080"

  mysql-server:
    image: mysql:latest
    environment:
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
